/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/antiforgery-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AntiforgeryToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/authed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthAuthed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permission/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PermissionCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogListServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/{databaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/{databaseId}/ddl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExportSchemaDdl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExecuteQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExplainQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetQueryHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/oauth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterClientRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/user/{userId}/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GrantPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/user/{userId}/permission/{permission}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RevokePermission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminListServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/database/{databaseId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListDatabaseRoles"];
        put?: never;
        post: operations["AssignDatabaseRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/database/{databaseId}/role/{userId}/{permission}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemoveDatabaseRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/user/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListUserRoles"];
        put?: never;
        post: operations["AssignUserRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAccessGroups"];
        put?: never;
        post: operations["CreateAccessGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/group/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAccessGroup"];
        put?: never;
        post?: never;
        delete: operations["DeleteAccessGroup"];
        options?: never;
        head?: never;
        patch: operations["UpdateAccessGroup"];
        trace?: never;
    };
    "/api/admin/group/{groupId}/member/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddAccessGroupMember"];
        delete: operations["RemoveAccessGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/group/{groupId}/permission/{permission}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GrantAccessGroupPermission"];
        delete: operations["RevokeAccessGroupPermission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/group/{groupId}/database/{databaseId}/role/{permission}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GrantAccessGroupDatabaseRole"];
        delete: operations["RevokeAccessGroupDatabaseRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/database/{databaseId}/sensitive-column": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListSensitiveColumns"];
        put?: never;
        post: operations["MarkSensitiveColumn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/database/{databaseId}/sensitive-column/{sensitiveColumnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UnmarkSensitiveColumn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/database/{databaseId}/sensitive-column/{sensitiveColumnId}/bypass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GrantColumnBypass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/database/{databaseId}/sensitive-column/{sensitiveColumnId}/bypass/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RevokeColumnBypass"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListServers"];
        put?: never;
        post: operations["CreateServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateServer"];
        post?: never;
        delete: operations["DeleteServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/{serverId}/credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/{serverId}/credential/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateCredential"];
        post?: never;
        delete: operations["DeleteCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/{serverId}/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/{serverId}/database/{databaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateDatabase"];
        post?: never;
        delete: operations["DeleteDatabase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/{serverId}/database/{databaseId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestDatabaseConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListUpdates"];
        put?: never;
        post: operations["SubmitUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetUpdate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ApproveUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RejectUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CancelUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExecuteUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessGroupId: unknown;
        AddCredentialRequest: {
            label: string;
            username: string;
            password: string;
        };
        AddDatabaseRequest: {
            displayName: string;
            databaseName: string;
            readCredentialId: components["schemas"]["CredentialId"];
            /** Format: uuid */
            writeCredentialId?: null | string;
        };
        AdminDatabaseItem: {
            id: components["schemas"]["DatabaseId"];
            displayName: string;
            isDisabled: boolean;
        };
        AdminServerItem: {
            id: components["schemas"]["ServerId"];
            name: string;
            isDisabled: boolean;
            databases: components["schemas"]["AdminDatabaseItem"][];
        };
        AdminServerListResponse: {
            servers: components["schemas"]["AdminServerItem"][];
        };
        AntiforgeryTokenResponse: {
            headerName: null | string;
        };
        AssignDatabaseRoleRequest: {
            userId: components["schemas"]["UserId"];
            permission: string;
        };
        AssignUserRoleRequest: {
            databaseId: components["schemas"]["DatabaseId"];
            permission: string;
        };
        BypassItem: {
            id: components["schemas"]["UserColumnBypassId"];
            userId: components["schemas"]["UserId"];
            userEmail: null | string;
            userName: null | string;
            /** Format: date-time */
            grantedAt: string;
            grantedById: null | components["schemas"]["UserId"];
        };
        CancelUpdateRequest: {
            note: string;
        };
        CatalogDatabaseItem: {
            id: components["schemas"]["DatabaseId"];
            displayName: string;
            canWrite: boolean;
        };
        CatalogServerItem: {
            id: components["schemas"]["ServerId"];
            name: string;
            databases: components["schemas"]["CatalogDatabaseItem"][];
        };
        CatalogServersResponse: {
            servers: components["schemas"]["CatalogServerItem"][];
        };
        ColumnInfo: {
            name: string;
            dataType: string;
            isNullable: boolean;
            /** @default false */
            isSensitive: boolean;
            /** @default false */
            isRestricted: boolean;
        };
        ConnectivityResult: {
            ok: boolean;
            error: null | string;
        };
        CreateGroupRequest: {
            name: string;
            description: null | string;
        };
        CreateServerRequest: {
            name: string;
            kind: string;
            host: string;
            /** Format: int32 */
            port: number | string;
        };
        /** Format: uuid */
        CredentialId: string;
        CredentialResponse: {
            id: components["schemas"]["CredentialId"];
            label: string;
            username: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** Format: uuid */
        DatabaseId: string;
        DatabaseResponse: {
            id: components["schemas"]["DatabaseId"];
            displayName: string;
            databaseName: string;
            readCredentialId: components["schemas"]["CredentialId"];
            writeCredentialId: null | components["schemas"]["CredentialId"];
            canWrite: boolean;
            isDisabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DatabaseRoleListResponse: {
            roles: components["schemas"]["EffectiveDatabaseRoleItem"][];
        };
        EffectiveDatabaseRoleItem: {
            userId: components["schemas"]["UserId"];
            userEmail: null | string;
            userName: null | string;
            permission: string;
            fromDirect: boolean;
            fromGroups: components["schemas"]["GroupRef"][];
        };
        EffectivePermission: {
            permission: string;
            fromDirect: boolean;
            fromGroups: components["schemas"]["GroupRef"][];
        };
        EffectiveUserRoleItem: {
            databaseId: components["schemas"]["DatabaseId"];
            databaseDisplayName: string;
            serverName: string;
            permission: string;
            fromDirect: boolean;
            fromGroups: components["schemas"]["GroupRef"][];
        };
        ExplainRequest: {
            databaseId: components["schemas"]["DatabaseId"];
            sql: string;
            analyze: boolean;
        };
        ExtensionInfo: {
            name: string;
            version: string;
            schema: string;
        };
        ForeignKey: {
            constraintName: string;
            columns: string[];
            referencedSchema: string;
            referencedTable: string;
            referencedColumns: string[];
        };
        GrantBypassRequest: {
            userId: components["schemas"]["UserId"];
        };
        GrantPermissionRequest: {
            permission: string;
        };
        GroupDatabaseRoleItem: {
            databaseId: components["schemas"]["DatabaseId"];
            permission: string;
        };
        GroupDetailResponse: {
            id: components["schemas"]["AccessGroupId"];
            name: string;
            description: null | string;
            members: components["schemas"]["GroupMemberItem"][];
            globalPermissions: string[];
            databaseRoles: components["schemas"]["GroupDatabaseRoleItem"][];
        };
        GroupListResponse: {
            groups: components["schemas"]["GroupSummary"][];
        };
        GroupMemberItem: {
            userId: components["schemas"]["UserId"];
            email: null | string;
            name: null | string;
        };
        GroupRef: {
            groupId: components["schemas"]["AccessGroupId"];
            name: string;
        };
        GroupSummary: {
            id: components["schemas"]["AccessGroupId"];
            name: string;
            description: null | string;
            /** Format: int32 */
            memberCount: number | string;
            /** Format: int32 */
            globalPermissionCount: number | string;
            /** Format: int32 */
            databaseRoleCount: number | string;
        };
        HealthResponse: {
            status: string;
            user: null | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        IndexInfo: {
            name: string;
            columns: string[];
            isUnique: boolean;
            isPrimary: boolean;
            method: string;
        };
        ListServersResponse: {
            servers: components["schemas"]["ServerResponse"][];
        };
        ListUpdateRequestsResponse: {
            requests: components["schemas"]["UpdateSummaryItem"][];
        };
        ListUsersResponse: {
            users: components["schemas"]["UserSummaryResponse"][];
        };
        MarkSensitiveColumnRequest: {
            schemaName: string;
            tableName: string;
            columnName: string;
        };
        MaterializedViewInfo: {
            name: string;
            columns: components["schemas"]["ColumnInfo"][];
            indexes: components["schemas"]["IndexInfo"][];
            definition?: null | string;
        };
        MeResponse: {
            id: components["schemas"]["UserId"];
            email: null | string;
            name: null | string;
            permissions: string[];
        };
        PermissionCatalogResponse: {
            permissions: string[];
        };
        PrimaryKey: {
            columns: string[];
        };
        QueryHistoryItem: {
            id: components["schemas"]["QueryLogId"];
            databaseId: null | components["schemas"]["DatabaseId"];
            databaseDisplayName: null | string;
            serverName: null | string;
            queryText: string;
            status: components["schemas"]["QueryLogStatus"];
            /** Format: date-time */
            executedAt: string;
            /** Format: int32 */
            durationMs: null | number | string;
            /** Format: int32 */
            rowCount: null | number | string;
            error: null | string;
            userId: null | components["schemas"]["UserId"];
            userName: null | string;
            sensitiveColumns: string[];
            source: components["schemas"]["QuerySource"];
        };
        QueryHistoryResponse: {
            items: components["schemas"]["QueryHistoryItem"][];
        };
        QueryLogId: unknown;
        /** @enum {string} */
        QueryLogStatus: "Unknown" | "Success" | "Error" | "Timeout" | "Blocked";
        QueryPlanResponse: {
            planJson: string;
            summary: components["schemas"]["QueryPlanSummary"];
        };
        QueryPlanSummary: {
            /** Format: double */
            totalCost: number | string;
            /** Format: double */
            estimatedRows: number | string;
            rootNode: string;
            hasSeqScan: boolean;
            /** Format: double */
            actualTotalMs: null | number | string;
        };
        QueryRequest: {
            databaseId: components["schemas"]["DatabaseId"];
            sql: string;
        };
        QueryResponse: {
            columns: null | string[];
            rows: null | (null | string)[][];
            /** Format: int32 */
            rowCount: number | string;
            /** Format: int32 */
            durationMs: number | string;
            error: null | string;
            estimate: null | components["schemas"]["QueryPlanSummary"];
        };
        /** @enum {string} */
        QuerySource: "Ui" | "Mcp";
        RegisterClientRequest: {
            client_name: null | string;
            redirect_uris: null | string[];
        };
        ReviewUpdateRequest: {
            note: string;
        };
        RoutineInfo: {
            name: string;
            kind: string;
            returnType: null | string;
            language: string;
            signature: string;
            definition?: null | string;
        };
        SchemaInfo: {
            name: string;
            tables: components["schemas"]["TableInfo"][];
            views: components["schemas"]["ViewInfo"][];
            materializedViews: components["schemas"]["MaterializedViewInfo"][];
            routines: components["schemas"]["RoutineInfo"][];
            sequences: components["schemas"]["SequenceInfo"][];
            types: components["schemas"]["TypeInfo"][];
        };
        SchemaTree: {
            schemas: components["schemas"]["SchemaInfo"][];
            extensions: components["schemas"]["ExtensionInfo"][];
        };
        SensitiveColumnId: unknown;
        SensitiveColumnItem: {
            id: components["schemas"]["SensitiveColumnId"];
            schemaName: string;
            tableName: string;
            columnName: string;
            /** Format: date-time */
            markedAt: string;
            markedById: null | components["schemas"]["UserId"];
            bypasses: components["schemas"]["BypassItem"][];
        };
        SensitiveColumnListResponse: {
            columns: components["schemas"]["SensitiveColumnItem"][];
        };
        SequenceInfo: {
            name: string;
            dataType: string;
            /** Format: int64 */
            start: number | string;
            /** Format: int64 */
            increment: number | string;
            /** Format: int64 */
            minValue: number | string;
            /** Format: int64 */
            maxValue: number | string;
            cycle: boolean;
            ownedByColumn: null | string;
        };
        /** Format: uuid */
        ServerId: string;
        ServerResponse: {
            id: components["schemas"]["ServerId"];
            name: string;
            kind: string;
            host: string;
            /** Format: int32 */
            port: number | string;
            isDisabled: boolean;
            credentials: components["schemas"]["CredentialResponse"][];
            databases: components["schemas"]["DatabaseResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SubmitUpdateRequest: {
            databaseId: components["schemas"]["DatabaseId"];
            sqlText: string;
            reason: string;
            /** Format: uuid */
            sourceRequestId?: null | string;
        };
        TableInfo: {
            name: string;
            columns: components["schemas"]["ColumnInfo"][];
            primaryKey: null | components["schemas"]["PrimaryKey"];
            foreignKeys: components["schemas"]["ForeignKey"][];
            indexes: components["schemas"]["IndexInfo"][];
        };
        TestConnectionResponse: {
            read: components["schemas"]["ConnectivityResult"];
            write: null | components["schemas"]["ConnectivityResult"];
        };
        TypeInfo: {
            name: string;
            kind: string;
            enumLabels: null | string[];
            attributes: null | string[];
            baseType: null | string;
        };
        UpdateCredentialRequest: {
            label: string;
            username: string;
            password?: null | string;
        };
        UpdateDatabaseRequest: {
            displayName: string;
            databaseName: string;
            readCredentialId: components["schemas"]["CredentialId"];
            writeCredentialId: null | components["schemas"]["CredentialId"];
            isDisabled: boolean;
        };
        UpdateGroupRequest: {
            name: string;
            description: null | string;
        };
        UpdateRequestDetailResponse: {
            id: components["schemas"]["UpdateRequestId"];
            databaseId: null | components["schemas"]["DatabaseId"];
            databaseDisplayName: null | string;
            submitterId: null | components["schemas"]["UserId"];
            submitterName: null | string;
            sqlText: string;
            reason: string;
            status: components["schemas"]["UpdateRequestStatus"];
            reviewerId: null | components["schemas"]["UserId"];
            reviewerName: null | string;
            reviewNote: null | string;
            cancelledById: null | components["schemas"]["UserId"];
            cancelledByName: null | string;
            cancelNote: null | string;
            executorId: null | components["schemas"]["UserId"];
            executorName: null | string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            reviewedAt: null | string;
            /** Format: date-time */
            executedAt: null | string;
            /** Format: date-time */
            cancelledAt: null | string;
            execSuccess: null | boolean;
            /** Format: int32 */
            execDurationMs: null | number | string;
            /** Format: int32 */
            execAffectedRows: null | number | string;
            execError: null | string;
            sourceRequestId: null | components["schemas"]["UpdateRequestId"];
        };
        /** Format: uuid */
        UpdateRequestId: string;
        /** @enum {string} */
        UpdateRequestStatus: "Pending" | "Approved" | "Rejected" | "Cancelled" | "Executed";
        UpdateServerRequest: {
            name: string;
            host: string;
            /** Format: int32 */
            port: number | string;
            kind: string;
            /** @default false */
            isDisabled: boolean;
        };
        UpdateSummaryItem: {
            id: components["schemas"]["UpdateRequestId"];
            databaseDisplayName: null | string;
            submitterName: null | string;
            reason: string;
            status: components["schemas"]["UpdateRequestStatus"];
            /** Format: date-time */
            submittedAt: string;
            execSuccess: null | boolean;
        };
        UserColumnBypassId: unknown;
        /** Format: uuid */
        UserId: string;
        UserRoleListResponse: {
            roles: components["schemas"]["EffectiveUserRoleItem"][];
        };
        UserSummaryResponse: {
            id: components["schemas"]["UserId"];
            email: null | string;
            name: null | string;
            /** Format: date-time */
            lastLoginAt: null | string;
            permissions: components["schemas"]["EffectivePermission"][];
        };
        ViewInfo: {
            name: string;
            columns: components["schemas"]["ColumnInfo"][];
            definition?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: {
                returnUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    AntiforgeryToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AntiforgeryTokenResponse"];
                };
            };
        };
    };
    Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthAuthed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    PermissionCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionCatalogResponse"];
                };
            };
        };
    };
    CatalogListServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogServersResponse"];
                };
            };
        };
    };
    GetSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaTree"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExportSchemaDdl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExecuteQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExplainQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPlanResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetQueryHistory: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                databaseId?: string;
                status?: string;
                source?: string;
                sensitiveColumn?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryHistoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    ListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponse"];
                };
            };
        };
    };
    GrantPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantPermissionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokePermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                permission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminListServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminServerListResponse"];
                };
            };
        };
    };
    ListDatabaseRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseRoleListResponse"];
                };
            };
        };
    };
    AssignDatabaseRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignDatabaseRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveDatabaseRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
                userId: string;
                permission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRoleListResponse"];
                };
            };
        };
    };
    AssignUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignUserRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListAccessGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
        };
    };
    CreateAccessGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAccessGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteAccessGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateAccessGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddAccessGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveAccessGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrantAccessGroupPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                permission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokeAccessGroupPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                permission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrantAccessGroupDatabaseRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                databaseId: string;
                permission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokeAccessGroupDatabaseRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                databaseId: string;
                permission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListSensitiveColumns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitiveColumnListResponse"];
                };
            };
        };
    };
    MarkSensitiveColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkSensitiveColumnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnmarkSensitiveColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
                sensitiveColumnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrantColumnBypass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
                sensitiveColumnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantBypassRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokeColumnBypass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
                sensitiveColumnId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListServersResponse"];
                };
            };
        };
    };
    CreateServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCredentialRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCredentialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AddDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDatabaseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDatabaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestDatabaseConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
                databaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListUpdates: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                databaseId?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUpdateRequestsResponse"];
                };
            };
        };
    };
    SubmitUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitUpdateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequestDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequestDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproveUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequestDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    RejectUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequestDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    CancelUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequestDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    ExecuteUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequestDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
