// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SluiceBase.Api.Data;

#nullable disable

namespace SluiceBase.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510170053_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_key");

                    b.ToTable("data_protection_key", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserPermissionMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permission");

                    b.HasIndex("GrantedById")
                        .HasDatabaseName("ix_user_permission_granted_by_id");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ix_user_permission_user_id_permission");

                    b.ToTable("user_permission", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Queries.QueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_query_log");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("ix_query_log_database_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_query_log_user_id");

                    b.ToTable("query_log", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_server_credential");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_credential_server_id");

                    b.ToTable("server_credential", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("database_name");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ReadCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("read_credential_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WriteCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("write_credential_id");

                    b.HasKey("Id")
                        .HasName("pk_server_database");

                    b.HasIndex("ReadCredentialId")
                        .HasDatabaseName("ix_server_database_read_credential_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_database_server_id");

                    b.HasIndex("WriteCredentialId")
                        .HasDatabaseName("ix_server_database_write_credential_id");

                    b.ToTable("server_database", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_server_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Updates.UpdateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelNote")
                        .HasColumnType("text")
                        .HasColumnName("cancel_note");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledById")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_id");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<int?>("ExecAffectedRows")
                        .HasColumnType("integer")
                        .HasColumnName("exec_affected_rows");

                    b.Property<int?>("ExecDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("exec_duration_ms");

                    b.Property<string>("ExecError")
                        .HasColumnType("text")
                        .HasColumnName("exec_error");

                    b.Property<bool?>("ExecSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("exec_success");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("SqlText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmitterId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitter_id");

                    b.HasKey("Id")
                        .HasName("pk_update_request");

                    b.HasIndex("CancelledById")
                        .HasDatabaseName("ix_update_request_cancelled_by_id");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("ix_update_request_database_id");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("ix_update_request_executor_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_update_request_reviewer_id");

                    b.HasIndex("SubmitterId")
                        .HasDatabaseName("ix_update_request_submitter_id");

                    b.ToTable("update_request", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sub");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Sub")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sub");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserPermissionMap", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_permission_user_granted_by_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Queries.QueryLog", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Database", null)
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_query_log_server_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_query_log_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Credential", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Server", null)
                        .WithMany("Credentials")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_server_credential_server_server_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Database", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Credential", null)
                        .WithMany()
                        .HasForeignKey("ReadCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_server_database_server_credential_read_credential_id");

                    b.HasOne("SluiceBase.Core.Servers.Server", "Server")
                        .WithMany("Databases")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_server_database_server_server_id");

                    b.HasOne("SluiceBase.Core.Servers.Credential", null)
                        .WithMany()
                        .HasForeignKey("WriteCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_server_database_server_credential_write_credential_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("SluiceBase.Core.Updates.UpdateRequest", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_cancelled_by_id");

                    b.HasOne("SluiceBase.Core.Servers.Database", "Database")
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_update_request_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_executor_id");

                    b.HasOne("SluiceBase.Core.Users.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_reviewer_id");

                    b.HasOne("SluiceBase.Core.Users.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_submitter_id");

                    b.Navigation("CancelledBy");

                    b.Navigation("Database");

                    b.Navigation("Executor");

                    b.Navigation("Reviewer");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Server", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Databases");
                });

            modelBuilder.Entity("SluiceBase.Core.Users.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
