// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SluiceBase.Api.Data;

#nullable disable

namespace SluiceBase.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_key");

                    b.ToTable("data_protection_key", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Mcp.McpAuthCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_challenge");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirect_uri");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mcp_auth_code");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_auth_code_code_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_auth_code_user_id");

                    b.ToTable("mcp_auth_code", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Mcp.McpOAuthClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("redirect_uris");

                    b.HasKey("Id")
                        .HasName("pk_mcp_oauth_client");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_oauth_client_client_id");

                    b.ToTable("mcp_oauth_client", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Mcp.McpToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mcp_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_token_token_hash");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("ix_mcp_token_user_id_type");

                    b.ToTable("mcp_token", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_access_group");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_access_group_created_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_access_group_name");

                    b.ToTable("access_group", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroupDatabaseRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.HasKey("Id")
                        .HasName("pk_access_group_database_role");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("ix_access_group_database_role_database_id");

                    b.HasIndex("GrantedById")
                        .HasDatabaseName("ix_access_group_database_role_granted_by_id");

                    b.HasIndex("GroupId", "Permission", "DatabaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_group_database_role_group_id_permission_database_id");

                    b.ToTable("access_group_database_role", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid?>("AddedById")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_group_member");

                    b.HasIndex("AddedById")
                        .HasDatabaseName("ix_access_group_member_added_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_group_member_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_group_member_group_id_user_id");

                    b.ToTable("access_group_member", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.HasKey("Id")
                        .HasName("pk_access_group_permission");

                    b.HasIndex("GrantedById")
                        .HasDatabaseName("ix_access_group_permission_granted_by_id");

                    b.HasIndex("GroupId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ix_access_group_permission_group_id_permission");

                    b.ToTable("access_group_permission", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.SensitiveColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("column_name");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<DateTimeOffset>("MarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at");

                    b.Property<Guid?>("MarkedById")
                        .HasColumnType("uuid")
                        .HasColumnName("marked_by_id");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("schema_name");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("pk_sensitive_column");

                    b.HasIndex("MarkedById")
                        .HasDatabaseName("ix_sensitive_column_marked_by_id");

                    b.HasIndex("DatabaseId", "SchemaName", "TableName", "ColumnName")
                        .IsUnique()
                        .HasDatabaseName("ix_sensitive_column_database_id_schema_name_table_name_column_");

                    b.ToTable("sensitive_column", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserColumnBypass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_id");

                    b.Property<Guid>("SensitiveColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensitive_column_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_column_bypass");

                    b.HasIndex("GrantedById")
                        .HasDatabaseName("ix_user_column_bypass_granted_by_id");

                    b.HasIndex("SensitiveColumnId")
                        .HasDatabaseName("ix_user_column_bypass_sensitive_column_id");

                    b.HasIndex("UserId", "SensitiveColumnId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_column_bypass_user_id_sensitive_column_id");

                    b.ToTable("user_column_bypass", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserDatabaseRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_database_role");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("ix_user_database_role_database_id");

                    b.HasIndex("GrantedById")
                        .HasDatabaseName("ix_user_database_role_granted_by_id");

                    b.HasIndex("UserId", "Permission", "DatabaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_database_role_user_id_permission_database_id");

                    b.ToTable("user_database_role", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserPermissionMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permission");

                    b.HasIndex("GrantedById")
                        .HasDatabaseName("ix_user_permission_granted_by_id");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ix_user_permission_user_id_permission");

                    b.ToTable("user_permission", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Queries.QueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.PrimitiveCollection<string[]>("SensitiveColumns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sensitive_columns");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Ui")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_query_log");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("ix_query_log_database_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_query_log_user_id");

                    b.ToTable("query_log", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_server_credential");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_credential_server_id");

                    b.ToTable("server_credential", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("database_name");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ReadCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("read_credential_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WriteCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("write_credential_id");

                    b.HasKey("Id")
                        .HasName("pk_server_database");

                    b.HasIndex("ReadCredentialId")
                        .HasDatabaseName("ix_server_database_read_credential_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_database_server_id");

                    b.HasIndex("WriteCredentialId")
                        .HasDatabaseName("ix_server_database_write_credential_id");

                    b.ToTable("server_database", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_server_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("server", (string)null);

                    b.HasDiscriminator<string>("kind").HasValue("Server");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SluiceBase.Core.Updates.UpdateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelNote")
                        .HasColumnType("text")
                        .HasColumnName("cancel_note");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledById")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_id");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<int?>("ExecAffectedRows")
                        .HasColumnType("integer")
                        .HasColumnName("exec_affected_rows");

                    b.Property<int?>("ExecDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("exec_duration_ms");

                    b.Property<string>("ExecError")
                        .HasColumnType("text")
                        .HasColumnName("exec_error");

                    b.Property<bool?>("ExecSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("exec_success");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid?>("SourceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_request_id");

                    b.Property<string>("SqlText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmitterId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitter_id");

                    b.HasKey("Id")
                        .HasName("pk_update_request");

                    b.HasIndex("CancelledById")
                        .HasDatabaseName("ix_update_request_cancelled_by_id");

                    b.HasIndex("DatabaseId")
                        .HasDatabaseName("ix_update_request_database_id");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("ix_update_request_executor_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_update_request_reviewer_id");

                    b.HasIndex("SourceRequestId")
                        .HasDatabaseName("ix_update_request_source_request_id");

                    b.HasIndex("SubmitterId")
                        .HasDatabaseName("ix_update_request_submitter_id");

                    b.ToTable("update_request", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Users.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_login_user_id");

                    b.HasIndex("Issuer", "Subject")
                        .HasDatabaseName("ix_external_login_issuer_subject");

                    b.ToTable("external_login", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.MongoServer", b =>
                {
                    b.HasBaseType("SluiceBase.Core.Servers.Server");

                    b.Property<string>("AuthSource")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth_source");

                    b.Property<string>("ConnectionMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("connection_mode");

                    b.Property<string>("ReplicaSet")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replica_set");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean")
                        .HasColumnName("use_tls");

                    b.ToTable("server", (string)null);

                    b.HasDiscriminator().HasValue("mongodb");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.PostgresServer", b =>
                {
                    b.HasBaseType("SluiceBase.Core.Servers.Server");

                    b.ToTable("server", (string)null);

                    b.HasDiscriminator().HasValue("postgres");
                });

            modelBuilder.Entity("SluiceBase.Core.Mcp.McpAuthCode", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mcp_auth_code_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Mcp.McpToken", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mcp_token_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroup", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_group_user_created_by_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroupDatabaseRole", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Database", null)
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_group_database_role_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_group_database_role_user_granted_by_id");

                    b.HasOne("SluiceBase.Core.Permissions.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_group_database_role_access_group_group_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroupMember", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_group_member_user_added_by_id");

                    b.HasOne("SluiceBase.Core.Permissions.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_group_member_access_group_group_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_group_member_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.AccessGroupPermission", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_group_permission_user_granted_by_id");

                    b.HasOne("SluiceBase.Core.Permissions.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_group_permission_access_group_group_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.SensitiveColumn", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Database", null)
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensitive_column_server_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("MarkedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sensitive_column_user_marked_by_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserColumnBypass", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_column_bypass_user_granted_by_id");

                    b.HasOne("SluiceBase.Core.Permissions.SensitiveColumn", null)
                        .WithMany()
                        .HasForeignKey("SensitiveColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_column_bypass_sensitive_column_sensitive_column_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_column_bypass_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserDatabaseRole", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Database", null)
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_database_role_server_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_database_role_user_granted_by_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_database_role_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Permissions.UserPermissionMap", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_permission_user_granted_by_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Queries.QueryLog", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Database", null)
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_query_log_server_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_query_log_user_user_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Credential", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Server", null)
                        .WithMany("Credentials")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_server_credential_server_server_id");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Database", b =>
                {
                    b.HasOne("SluiceBase.Core.Servers.Credential", null)
                        .WithMany()
                        .HasForeignKey("ReadCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_server_database_server_credential_read_credential_id");

                    b.HasOne("SluiceBase.Core.Servers.Server", "Server")
                        .WithMany("Databases")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_server_database_server_server_id");

                    b.HasOne("SluiceBase.Core.Servers.Credential", null)
                        .WithMany()
                        .HasForeignKey("WriteCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_server_database_server_credential_write_credential_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("SluiceBase.Core.Updates.UpdateRequest", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_cancelled_by_id");

                    b.HasOne("SluiceBase.Core.Servers.Database", "Database")
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_update_request_database_database_id");

                    b.HasOne("SluiceBase.Core.Users.User", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_executor_id");

                    b.HasOne("SluiceBase.Core.Users.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_reviewer_id");

                    b.HasOne("SluiceBase.Core.Updates.UpdateRequest", "SourceRequest")
                        .WithMany()
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_update_request_update_request_source_request_id");

                    b.HasOne("SluiceBase.Core.Users.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_update_request_user_submitter_id");

                    b.Navigation("CancelledBy");

                    b.Navigation("Database");

                    b.Navigation("Executor");

                    b.Navigation("Reviewer");

                    b.Navigation("SourceRequest");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("SluiceBase.Core.Users.ExternalLogin", b =>
                {
                    b.HasOne("SluiceBase.Core.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_login_user_user_id");

                    b.OwnsMany("SluiceBase.Core.Users.ClaimRecord", "Claims", b1 =>
                        {
                            b1.Property<Guid>("ExternalLoginId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasJsonPropertyName("type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasJsonPropertyName("value");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasJsonPropertyName("valueType");

                            b1.HasKey("ExternalLoginId", "__synthesizedOrdinal");

                            b1.ToTable("external_login");

                            b1
                                .ToJson("claims")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExternalLoginId")
                                .HasConstraintName("fk_external_login_external_login_external_login_id");
                        });

                    b.Navigation("Claims");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SluiceBase.Core.Servers.Server", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Databases");
                });

            modelBuilder.Entity("SluiceBase.Core.Users.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
