/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedServerRouteImport } from './routes/_authed/server'
import { Route as AuthedQueryRouteImport } from './routes/_authed/query'
import { Route as AuthedPermissionRouteImport } from './routes/_authed/permission'
import { Route as AuthedHealthRouteImport } from './routes/_authed/health'
import { Route as AuthedUpdateIndexRouteImport } from './routes/_authed/update/index'
import { Route as AuthedUpdateNewRouteImport } from './routes/_authed/update/new'
import { Route as AuthedUpdateIdRouteImport } from './routes/_authed/update/$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServerRoute = AuthedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQueryRoute = AuthedQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPermissionRoute = AuthedPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHealthRoute = AuthedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateIndexRoute = AuthedUpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateNewRoute = AuthedUpdateNewRouteImport.update({
  id: '/update/new',
  path: '/update/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateIdRoute = AuthedUpdateIdRouteImport.update({
  id: '/update/$id',
  path: '/update/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/health': typeof AuthedHealthRoute
  '/permission': typeof AuthedPermissionRoute
  '/query': typeof AuthedQueryRoute
  '/server': typeof AuthedServerRoute
  '/update/$id': typeof AuthedUpdateIdRoute
  '/update/new': typeof AuthedUpdateNewRoute
  '/update/': typeof AuthedUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof AuthedHealthRoute
  '/permission': typeof AuthedPermissionRoute
  '/query': typeof AuthedQueryRoute
  '/server': typeof AuthedServerRoute
  '/': typeof AuthedIndexRoute
  '/update/$id': typeof AuthedUpdateIdRoute
  '/update/new': typeof AuthedUpdateNewRoute
  '/update': typeof AuthedUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/health': typeof AuthedHealthRoute
  '/_authed/permission': typeof AuthedPermissionRoute
  '/_authed/query': typeof AuthedQueryRoute
  '/_authed/server': typeof AuthedServerRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/update/$id': typeof AuthedUpdateIdRoute
  '/_authed/update/new': typeof AuthedUpdateNewRoute
  '/_authed/update/': typeof AuthedUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/permission'
    | '/query'
    | '/server'
    | '/update/$id'
    | '/update/new'
    | '/update/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/permission'
    | '/query'
    | '/server'
    | '/'
    | '/update/$id'
    | '/update/new'
    | '/update'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/health'
    | '/_authed/permission'
    | '/_authed/query'
    | '/_authed/server'
    | '/_authed/'
    | '/_authed/update/$id'
    | '/_authed/update/new'
    | '/_authed/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/server': {
      id: '/_authed/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthedServerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/query': {
      id: '/_authed/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AuthedQueryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/permission': {
      id: '/_authed/permission'
      path: '/permission'
      fullPath: '/permission'
      preLoaderRoute: typeof AuthedPermissionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/health': {
      id: '/_authed/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthedHealthRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update/': {
      id: '/_authed/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof AuthedUpdateIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update/new': {
      id: '/_authed/update/new'
      path: '/update/new'
      fullPath: '/update/new'
      preLoaderRoute: typeof AuthedUpdateNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update/$id': {
      id: '/_authed/update/$id'
      path: '/update/$id'
      fullPath: '/update/$id'
      preLoaderRoute: typeof AuthedUpdateIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedHealthRoute: typeof AuthedHealthRoute
  AuthedPermissionRoute: typeof AuthedPermissionRoute
  AuthedQueryRoute: typeof AuthedQueryRoute
  AuthedServerRoute: typeof AuthedServerRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedUpdateIdRoute: typeof AuthedUpdateIdRoute
  AuthedUpdateNewRoute: typeof AuthedUpdateNewRoute
  AuthedUpdateIndexRoute: typeof AuthedUpdateIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHealthRoute: AuthedHealthRoute,
  AuthedPermissionRoute: AuthedPermissionRoute,
  AuthedQueryRoute: AuthedQueryRoute,
  AuthedServerRoute: AuthedServerRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedUpdateIdRoute: AuthedUpdateIdRoute,
  AuthedUpdateNewRoute: AuthedUpdateNewRoute,
  AuthedUpdateIndexRoute: AuthedUpdateIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
