/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedServerRouteImport } from './routes/_authed/server'
import { Route as AuthedPermissionRouteImport } from './routes/_authed/permission'
import { Route as AuthedHealthRouteImport } from './routes/_authed/health'
import { Route as AuthedGroupRouteImport } from './routes/_authed/group'
import { Route as AuthedAccessRouteImport } from './routes/_authed/access'
import { Route as AuthedUpdateIndexRouteImport } from './routes/_authed/update/index'
import { Route as AuthedQueryIndexRouteImport } from './routes/_authed/query/index'
import { Route as AuthedUpdateNewRouteImport } from './routes/_authed/update/new'
import { Route as AuthedUpdateIdRouteImport } from './routes/_authed/update/$id'
import { Route as AuthedQueryHistoryRouteImport } from './routes/_authed/query/history'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServerRoute = AuthedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPermissionRoute = AuthedPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHealthRoute = AuthedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupRoute = AuthedGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccessRoute = AuthedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateIndexRoute = AuthedUpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQueryIndexRoute = AuthedQueryIndexRouteImport.update({
  id: '/query/',
  path: '/query/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateNewRoute = AuthedUpdateNewRouteImport.update({
  id: '/update/new',
  path: '/update/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateIdRoute = AuthedUpdateIdRouteImport.update({
  id: '/update/$id',
  path: '/update/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQueryHistoryRoute = AuthedQueryHistoryRouteImport.update({
  id: '/query/history',
  path: '/query/history',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/access': typeof AuthedAccessRoute
  '/group': typeof AuthedGroupRoute
  '/health': typeof AuthedHealthRoute
  '/permission': typeof AuthedPermissionRoute
  '/server': typeof AuthedServerRoute
  '/query/history': typeof AuthedQueryHistoryRoute
  '/update/$id': typeof AuthedUpdateIdRoute
  '/update/new': typeof AuthedUpdateNewRoute
  '/query/': typeof AuthedQueryIndexRoute
  '/update/': typeof AuthedUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/access': typeof AuthedAccessRoute
  '/group': typeof AuthedGroupRoute
  '/health': typeof AuthedHealthRoute
  '/permission': typeof AuthedPermissionRoute
  '/server': typeof AuthedServerRoute
  '/': typeof AuthedIndexRoute
  '/query/history': typeof AuthedQueryHistoryRoute
  '/update/$id': typeof AuthedUpdateIdRoute
  '/update/new': typeof AuthedUpdateNewRoute
  '/query': typeof AuthedQueryIndexRoute
  '/update': typeof AuthedUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/access': typeof AuthedAccessRoute
  '/_authed/group': typeof AuthedGroupRoute
  '/_authed/health': typeof AuthedHealthRoute
  '/_authed/permission': typeof AuthedPermissionRoute
  '/_authed/server': typeof AuthedServerRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/query/history': typeof AuthedQueryHistoryRoute
  '/_authed/update/$id': typeof AuthedUpdateIdRoute
  '/_authed/update/new': typeof AuthedUpdateNewRoute
  '/_authed/query/': typeof AuthedQueryIndexRoute
  '/_authed/update/': typeof AuthedUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/group'
    | '/health'
    | '/permission'
    | '/server'
    | '/query/history'
    | '/update/$id'
    | '/update/new'
    | '/query/'
    | '/update/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access'
    | '/group'
    | '/health'
    | '/permission'
    | '/server'
    | '/'
    | '/query/history'
    | '/update/$id'
    | '/update/new'
    | '/query'
    | '/update'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/access'
    | '/_authed/group'
    | '/_authed/health'
    | '/_authed/permission'
    | '/_authed/server'
    | '/_authed/'
    | '/_authed/query/history'
    | '/_authed/update/$id'
    | '/_authed/update/new'
    | '/_authed/query/'
    | '/_authed/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/server': {
      id: '/_authed/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthedServerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/permission': {
      id: '/_authed/permission'
      path: '/permission'
      fullPath: '/permission'
      preLoaderRoute: typeof AuthedPermissionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/health': {
      id: '/_authed/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthedHealthRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/group': {
      id: '/_authed/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof AuthedGroupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/access': {
      id: '/_authed/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthedAccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update/': {
      id: '/_authed/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof AuthedUpdateIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/query/': {
      id: '/_authed/query/'
      path: '/query'
      fullPath: '/query/'
      preLoaderRoute: typeof AuthedQueryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update/new': {
      id: '/_authed/update/new'
      path: '/update/new'
      fullPath: '/update/new'
      preLoaderRoute: typeof AuthedUpdateNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update/$id': {
      id: '/_authed/update/$id'
      path: '/update/$id'
      fullPath: '/update/$id'
      preLoaderRoute: typeof AuthedUpdateIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/query/history': {
      id: '/_authed/query/history'
      path: '/query/history'
      fullPath: '/query/history'
      preLoaderRoute: typeof AuthedQueryHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccessRoute: typeof AuthedAccessRoute
  AuthedGroupRoute: typeof AuthedGroupRoute
  AuthedHealthRoute: typeof AuthedHealthRoute
  AuthedPermissionRoute: typeof AuthedPermissionRoute
  AuthedServerRoute: typeof AuthedServerRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedQueryHistoryRoute: typeof AuthedQueryHistoryRoute
  AuthedUpdateIdRoute: typeof AuthedUpdateIdRoute
  AuthedUpdateNewRoute: typeof AuthedUpdateNewRoute
  AuthedQueryIndexRoute: typeof AuthedQueryIndexRoute
  AuthedUpdateIndexRoute: typeof AuthedUpdateIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccessRoute: AuthedAccessRoute,
  AuthedGroupRoute: AuthedGroupRoute,
  AuthedHealthRoute: AuthedHealthRoute,
  AuthedPermissionRoute: AuthedPermissionRoute,
  AuthedServerRoute: AuthedServerRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedQueryHistoryRoute: AuthedQueryHistoryRoute,
  AuthedUpdateIdRoute: AuthedUpdateIdRoute,
  AuthedUpdateNewRoute: AuthedUpdateNewRoute,
  AuthedQueryIndexRoute: AuthedQueryIndexRoute,
  AuthedUpdateIndexRoute: AuthedUpdateIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
